# Generated by Django 4.1.1 on 2022-09-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SumoInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('url', models.TextField()),
                ('tag', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='AccessKey',
        ),
    ]
