# Generated by Django 4.1.1 on 2022-09-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manager', '0002_sumoinstance_delete_accesskey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sumoinstance',
            name='id',
        ),
        migrations.AlterField(
            model_name='sumoinstance',
            name='tag',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
